// src/components/layout/Footer.vue
<template>
  <footer class="footer">
    <RouterLink class="footer__logo-wrapper" :to="routes.MAIN">
      <img class="footer__logo" src="/images/logo.png" alt="logo" />
    </RouterLink>

    <nav class="footer__nav">
      <template v-for="(item, index) in navigation" :key="index">
        <CButton class="footer__button" :to="item.to">
          <span class="footer__font footer__font--button">
            {{ item.text }}
          </span>
        </CButton>
      </template>
    </nav>
  </footer>
</template>

<script>
import routes from "@/constants/routes.js";
import navigation from "@/config/navigation.js";

import CButton from "@/components/ui/CButton.vue";

export default {
  name: "Footer",
  components: { CButton },
  setup() {
    return {
      navigation: navigation.footer,
      routes,
    };
  },
};
</script>

<style lang="scss">
.footer {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: em(31) 0 em(52);
  border-top: 1px solid $color-white;

  &__logo {
    width: em(143);
  }

  &__nav {
    display: flex;
    align-items: center;
  }

  &__button {
    &:not(:last-child) {
      margin-right: em(45);
    }
  }
}
</style>

// src/components/layout/Footer.jsx
import React from 'react'
import { Link } from 'react-router-dom'
import routes from '../../constants/routes'
import navigation from '../../config/navigation'
import CButton from '../ui/CButton'
import classNames from 'classnames'

function Footer({ className }) {
  return (
    <footer className={classNames(className, 'footer')}>
      <a className="footer__logo-wrapper" href={routes.MAIN}>
        <img className="footer__logo" src="/images/logo.png" alt="logo" />
      </a>
      <nav className="footer__nav">
        {navigation.footer.map((item, index) => (
          <CButton key={index} className="footer__button" to={item.to}>
            <span className="footer__font footer__font--button">
              {item.text}
            </span>
          </CButton>
        ))}
      </nav>
    </footer>
  )
}

export default Footer
