// src/components/sections/mint/SectionsMintPacks.jsx
import React from 'react'
import packs from '../../../config/packs'
import IconList from '../../blocks/IconList'
import classNames from 'classnames'

const SectionsMintPacks = ({ className }) => (
  <section className={classNames(className, 'sections-mint-packs')}>
    <div className="sections-mint-packs__container">
      <div className="sections-mint-packs__title-wrapper">
        <div className="sections-mint-packs__title">
          <span className="sections-mint-packs__font sections-mint-packs__font--title">
            BONUS PACKS
          </span>
        </div>

        <div className="sections-mint-packs__text">
          <span className="sections-mint-packs__font sections-mint-packs__font--text">
            Qualify for the following Bonus Packs by purchasing the Bonus Pack
            number of Legion Universe Digital Trading Cards. A Bonus Pack gives
            you additional physical bonuses (items mailed to you) as well as
            potential opportunities to join with us in the physical production
            and premiers of the films.
          </span>
        </div>
      </div>

      <div className="sections-mint-packs__content">
        {packs.map((pack, index) => (
          <IconList
            key={index}
            className="sections-mint-packs__list"
            iconName={pack.iconName}
            title={pack.title}
            list={pack.list}
          />
        ))}
      </div>

      <div className="sections-mint-packs__interrupter">
        <img
          className="sections-mint-packs__interrupter-bg"
          src="/images/page-bg/interrupter.png"
          alt="bg"
        />

        <img
          className="sections-mint-packs__interrupter-bg sections-mint-packs__interrupter-bg--mobile"
          src="/images/page-bg/interrupter-mobile.jpg"
          alt="bg"
        />

        <div className="sections-mint-packs__interrupter-title">
          <span className="sections-mint-packs__font sections-mint-packs__font--interrupter-title">
            Buy 50 Digital Trading Cards
          </span>
        </div>

        <div className="sections-mint-packs__interrupter-text">
          <span className="sections-mint-packs__font sections-mint-packs__font--interrupter-text">
            You are guaranteed to receive an opportunity for a{' '}
            <span className="sections-mint-packs__interrupter-accent">
              CAMEO ROLE
            </span>{' '}
            in one of the <br />
            films as well as an invitation to one of the{' '}
            <span className="sections-mint-packs__interrupter-accent">
              RED CARPET SCREENINGS!
            </span>
          </span>
        </div>

        <div className="sections-mint-packs__interrupter-text">
          <span className="sections-mint-packs__font sections-mint-packs__font--interrupter-text">
            <span className="sections-mint-packs__interrupter-accent">
              PLUS
            </span>{' '}
            an in person dinner with producers, directors, writers and VFX.{' '}
            <span className="sections-mint-packs__interrupter-accent">
              PLUS
            </span>{' '}
            with the investment <br />
            club, access to information, investments and funds thatare not
            available to the general public.
          </span>
        </div>
      </div>
    </div>
  </section>
)

export default SectionsMintPacks

// src/components/sections/mint/SectionsMintPacks.vue
<template>
  <section class="sections-mint-packs">
    <div class="sections-mint-packs__container">
      <div class="sections-mint-packs__title-wrapper">
        <div class="sections-mint-packs__title">
          <span
            class="sections-mint-packs__font sections-mint-packs__font--title"
          >
            BONUS PACKS
          </span>
        </div>

        <div class="sections-mint-packs__text">
          <span
            class="sections-mint-packs__font sections-mint-packs__font--text"
          >
            Qualify for the following Bonus Packs by purchasing the Bonus Pack
            number of Legion Universe Digital Trading Cards. A Bonus Pack gives
            you additional physical bonuses (items mailed to you) as well as
            potential opportunities to join with us in the physical production
            and premiers of the films.
          </span>
        </div>
      </div>

      <div class="sections-mint-packs__content">
        <template v-for="(pack, index) in packs" :key="index">
          <IconList
            class="sections-mint-packs__list"
            :icon-name="pack.iconName"
            :title="pack.title"
            :list="pack.list"
          />
        </template>
      </div>

      <div class="sections-mint-packs__interrupter">
        <img
          class="sections-mint-packs__interrupter-bg"
          src="/images/page-bg/interrupter.png"
          alt="bg"
        />

        <div class="sections-mint-packs__interrupter-title">
          <span
            class="sections-mint-packs__font sections-mint-packs__font--interrupter-title"
          >
            Buy 50 Digital Trading Cards
          </span>
        </div>

        <div class="sections-mint-packs__interrupter-text">
          <span
            class="sections-mint-packs__font sections-mint-packs__font--interrupter-text"
          >
            You are guaranteed to receive an opportunity for a
            <span class="sections-mint-packs__interrupter-accent">
              CAMEO ROLE
            </span>
            in one of the <br />
            films as well as an invitation to one of the
            <span class="sections-mint-packs__interrupter-accent">
              RED CARPET SCREENINGS!
            </span>
          </span>
        </div>

        <div class="sections-mint-packs__interrupter-text">
          <span
            class="sections-mint-packs__font sections-mint-packs__font--interrupter-text"
          >
            <span class="sections-mint-packs__interrupter-accent">PLUS</span> an
            in person dinner with producers, directors, writers and VFX.
            <span class="sections-mint-packs__interrupter-accent">PLUS</span>
            with the investment <br />
            club, access to information, investments and funds thatare not
            available to the general public.
          </span>
        </div>
      </div>
    </div>
  </section>
</template>

<script>
import packs from "@/config/packs.js";
import IconList from "@/components/blocks/IconList.vue";
export default {
  name: "SectionsMintPacks",
  components: { IconList },
  setup() {
    return {
      packs,
    };
  },
};
</script>

<style lang="scss">
.sections-mint-packs {
  position: relative;
  padding: 0 em(135);

  @include mobile {
    padding: 0 em(20);
  }

  &:before {
    background-image: url("/images/page-bg/mint-middle.png");
    background-repeat: no-repeat;
    background-size: cover;
    position: absolute;
    top: em(150);
    left: 0;
    width: 100%;
    height: em(1800);
    z-index: 1;
    content: "";

    @include mobile {
      top: em(-70);
    }
  }

  &__container {
    position: relative;
    z-index: 2;
  }

  &__title-wrapper {
    display: flex;
    align-items: center;
    margin-bottom: em(48);

    @include mobile {
      align-items: flex-start;
      flex-direction: column;
      margin-bottom: em(42);
    }
  }

  &__content {
    display: flex;
    margin-bottom: em(200);

    @include mobile {
      flex-direction: column;
      margin-bottom: em(161);
    }
  }

  &__list {
    width: 100%;

    &:not(:last-child) {
      margin-right: em(52);

      @include mobile {
        margin-right: 0;
        margin-bottom: em(43);
      }
    }
  }

  &__title {
    background: linear-gradient(
      92.97deg,
      #ffffff 2.9%,
      rgba(255, 255, 255, 0) 109.66%
    );
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    margin-right: em(41);
    white-space: nowrap;

    @include mobile {
      margin-bottom: em(50);
    }
  }

  &__interrupter {
    position: relative;
    border-radius: em(20);
    display: flex;
    flex-direction: column;
    align-items: center;
    padding: em(121) 0 em(65);

    @include mobile {
      padding: em(121) 0 em(99);
      width: calc(100% + #{em(20)});
      margin-left: em(-10);
      background-position: center;
      background-size: cover;
    }
  }

  &__interrupter-bg {
    position: absolute;
    z-index: 1;
    top: 50%;
    transform: translateY(-60%);
    left: 0;
    width: 100%;
    height: 142%;
    object-fit: contain;
  }

  &__interrupter-title {
    position: relative;
    z-index: 2;
    text-align: center;

    @include mobile {
      margin-bottom: em(15);
    }
  }

  &__interrupter-text {
    position: relative;
    z-index: 2;
    text-align: center;

    @include mobile {
      max-width: em(293);
    }
  }

  &__interrupter-accent {
    text-decoration: underline;
    text-underline-offset: 6px;
    text-decoration-thickness: 3px;
    text-decoration-color: $color-accent;
  }

  &__font {
    &--title {
      font-family: Squada One, sans-serif;
      font-size: em(95);
      line-height: em(158, 95);

      @include mobile {
        font-size: em(55);
        line-height: 1;
      }
    }

    &--text {
      font-size: em(15);
      line-height: em(28, 15);
    }

    &--interrupter-title {
      font-family: Squada One, sans-serif;
      font-size: em(75);
      line-height: em(81, 75);

      @include mobile {
        font-size: em(55);
        line-height: em(66, 55);
      }
    }

    &--interrupter-text {
      font-size: em(20);
      line-height: em(39, 20);

      @include mobile {
        font-size: em(15);
        line-height: em(26, 15);
      }
    }
  }
}
</style>
